server:
  port: 8090
  servlet:
    context-path: /invoice

security:
  jwt:
    token:
      secret-key: _@urhbKoa))65%&&34#$"!*OKP
      expire-length: 3000000
      refresh-expire-length: 3600000

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/invoice?allowPublicKeyRetrieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=UTC
    username: root
    password: password

ignored:
  paths: /invoice/login, /invoice/refreshToken, /invoice/save
