server:
  error:
    include-message: always
    include-binding-errors: always
  port: 9000
  max-http-header-size: 10MB
  servlet:
    context-path: /invoice

#logging:
#  level:
#    root: TRACE

security:
  jwt:
    token:
      secret-key: _@urhbKoa))65%&&34#$"!*OKP
      expire-length: 3000000
      refresh-expire-length: 3600000

spring:
  main:
    allow-circular-references: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://vps-034abdfe.vps.ovh.net:3306/invoice?allowPublicKeyRetrieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=UTC
    username: invoice
    password: qNAte6p?WIitih!FOjhf

ignored:    
    paths: /invoice/login, /invoice/refreshToken, /invoice/empresa/salvar/login
